/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'usuario' at '11/01/17 21:33' with Gradle 2.10
 *
 * @author usuario, @date 11/01/17 21:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
